"""Add PropertyDetails table

Revision ID: 50acab32ba2d
Revises: 08fa8f605ee8
Create Date: 2024-11-11 09:23:13.920025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50acab32ba2d'
down_revision = '08fa8f605ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('garage', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_status', sa.String(length=50), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('floor_plan', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('virtual_tour_url', sa.String(length=255), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('basement', sa.Boolean(), nullable=True),
    sa.Column('roofing', sa.String(length=100), nullable=True),
    sa.Column('parking', sa.String(length=100), nullable=True),
    sa.Column('heating', sa.String(length=100), nullable=True),
    sa.Column('cooling', sa.String(length=100), nullable=True),
    sa.Column('interior_features', sa.Text(), nullable=True),
    sa.Column('exterior_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=True))

    op.drop_table('property_details')
    # ### end Alembic commands ###
