"""Initial migration

Revision ID: 6f20683d14ac
Revises: 
Create Date: 2024-11-07 13:45:44.653525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f20683d14ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_proof_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('agency_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('agency_name')
        batch_op.drop_column('id_proof_file')
        batch_op.drop_column('license_file')

    # ### end Alembic commands ###
